#!/usr/bin/env python3
"""FM index generator: parse references/failure-modes{,_EN}.md into their INDEX sections.

Usage:
  python scripts/fm_index.py --check     # CI mode: exit 1 if an INDEX is out of sync
  python scripts/fm_index.py --write     # regenerate both INDEX sections in place
  python scripts/fm_index.py             # print the CN index to stdout

The CN and EN libraries must carry the SAME entry set — an EN-only or
CN-only failure mode means one language teaches a lesson the other hides.
That is how the two files silently drifted before: the EN copy lagged behind
both the redaction pass and FM-30, so `--check` now also asserts the counts
match.

Rules (see the intake protocol in references/failure-modes.md):
  - Heading form: '## FM-<N> <title>'
  - INDEX is delimited by its own heading up to the next '## ' heading
  - Each index line: '| FM-N | title |'
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROW_RE = re.compile(r"^## (FM-\d+) (.+?)\s*$", re.M)

VARIANTS = (
    ("CN", ROOT / "references" / "failure-modes.md",
     "## INDEX（由 scripts/fm_index.py 自动生成，勿手改）",
     "| 编号 | 一句话标题 |"),
    ("EN", ROOT / "references" / "failure-modes_EN.md",
     "## INDEX (auto-generated by scripts/fm_index.py — do not hand-edit)",
     "| ID | One-line title |"),
)


def parse(text: str):
    return [(m.group(1), m.group(2)) for m in ROW_RE.finditer(text)]


def render(entries, head: str, table_head: str) -> str:
    lines = [head, "", table_head, "|---|---|"]
    lines += [f"| {n} | {t} |" for n, t in entries]
    lines.append("")
    return "\n".join(lines)


def section_bounds(text: str, head: str):
    start = text.find(head)
    if start == -1:
        return None
    nxt = text.find("\n## ", start + len(head))
    end = len(text) if nxt == -1 else nxt + 1
    return start, end


def handle(tag: str, path: Path, head: str, table_head: str, mode: str) -> int:
    """Return an exit code on failure, else 0."""
    text = path.read_text(encoding="utf-8")
    entries = parse(text)
    idx = render(entries, head, table_head)
    bounds = section_bounds(text, head)
    if mode == "--check":
        if bounds is None:
            print(f"FAIL[{tag}]: INDEX section missing")
            return 1
        if text[bounds[0]:bounds[1]].rstrip() != idx.rstrip():
            print(f"FAIL[{tag}]: INDEX out of sync ({len(entries)} entries) — run: make fm-index")
            return 1
        return 0
    if mode == "--write":
        if bounds is None:
            first = text.find("\n## FM-1 ")
            if first == -1:
                print(f"FAIL[{tag}]: FM-1 not found")
                return 1
            text = text[:first] + "\n" + idx + text[first:]
        else:
            s, e = bounds
            text = text[:s] + idx + text[e:]
        path.write_text(text, encoding="utf-8")
        print(f"written[{tag}]: INDEX regenerated ({len(entries)} entries)")
        return 0
    if tag == "CN":
        print(idx)
    return 0


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else ""
    rc = 0
    counts = {}
    for tag, path, head, table_head in VARIANTS:
        rc |= handle(tag, path, head, table_head, mode)
        counts[tag] = len(parse(path.read_text(encoding="utf-8")))
    if mode == "--check":
        cn, en = counts["CN"], counts["EN"]
        if cn != en:
            print(f"FAIL: entry-count drift CN={cn} EN={en} — the two libraries must match")
            rc = 1
        elif rc == 0:
            print(f"OK: INDEX in sync, CN/EN both {cn} entries")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())